chore(build): Produce a functioning docker image
seiama/javaducks pull request #1
Opened 2023-09-25 05:40 UTC by zml2008

Haven't touched publishing or versioning this image yet, but this does the basic jib scaffolding.

2023-09-25 05:43 UTC, kashike requested changes

2023-09-25 05:43 UTC, kashike commented on build.gradle.kts
> +    image = "eclipse-temurin:${indra.javaVersions().target().get()}-jre"
I would prefer to use Azul Zulu, if it is an option.

2023-11-17 19:36 UTC, kashike approved these changes

2023-11-17 19:37 UTC, zml2008 commented
this needs a big more tweaking

2024-01-27 21:46 UTC, kashike approved these changes

2024-01-27 21:46 UTC, merged