Misc Changes (closes #2)
seiama/javaducks pull request #3
Opened 2024-01-27 10:25 UTC by MiniDigger

best reviewed individually, can drop stuff if you don't like the changes.

This implements #2 and should also fix the short 500s while updating, since the file is now fully written first before the old file is overridden, reducing the time an partly downloaded file is on the disk.

2024-01-27 20:59 UTC, MiniDigger commented
played around with graalvm, might be worth to consider to when we put it into a container, makes it only use 47mb of ram and starts in 0.1 seconds
![image](https://github.com/seiama/javaducks/assets/2185527/735f63d0-77db-44f1-a334-6ee557d238ee)

2024-01-27 21:43 UTC, kashike requested changes

2024-01-27 21:43 UTC, kashike commented on src/main/java/com/seiama/javaducks/service/JavadocService.java
> +          if (response.statusCode() != 200) {
Can we use constants instead of magic numbers?

2024-01-27 21:43 UTC, kashike commented on src/main/java/com/seiama/javaducks/service/JavadocService.java
> +          if (response.statusCode() != 200) {
Can we use constants instead of magic numbers?

2024-01-27 21:43 UTC, kashike commented on src/main/java/com/seiama/javaducks/util/HashUtil.java
> +      // utility class
```suggestion
```

2024-01-27 22:21 UTC, MiniDigger commented
somebody needs to figure out how to make checkstyle ignore the aot project

2024-01-28 03:53 UTC, kashike approved these changes

2024-01-28 06:41 UTC, kashike requested changes

2024-01-28 06:41 UTC, kashike commented on src/main/java/com/seiama/javaducks/JavaDucksRuntimeHints.java
> +    public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
Your formatting is off for this entire class - please run `build` and fix the checkstyle issues.

2024-01-28 06:41 UTC, kashike commented on src/main/java/com/seiama/javaducks/JavaDucksRuntimeHints.java
> +              .registerConstructor(Class.forName("com.github.benmanes.caffeine.cache.PSR").getDeclaredConstructors()[0], ExecutableMode.INVOKE);
Alphabetical.
```suggestion
              .registerConstructor(Class.forName("com.github.benmanes.caffeine.cache.PSR").getDeclaredConstructors()[0], ExecutableMode.INVOKE)
              .registerConstructor(Class.forName("com.github.benmanes.caffeine.cache.SSLR").getDeclaredConstructors()[0], ExecutableMode.INVOKE);
```

2024-01-28 21:33 UTC, kashike approved these changes

2024-01-28 21:33 UTC, merged