feat: add injection framework, inject favicon and duck
seiama/javaducks pull request #4
Opened 2024-02-18 10:37 UTC by MiniDigger

2024-05-05 23:29 UTC, powercasgamer commented
For the favicon injection it should probably check if the favicon exists before trying to add it. Perhaps something like [this?](https://github.com/seiama/javaducks/commit/d1e59b1a49df7a3f2946e3e799af52bdffc44fa2)

2024-05-11 16:56 UTC, MiniDigger commented
> For the favicon injection it should probably check if the favicon exists before trying to add it. Perhaps something like [this?](https://github.com/seiama/javaducks/commit/d1e59b1a49df7a3f2946e3e799af52bdffc44fa2)

I dont think that makes a difference (the browser will always try to fetch a favicon, even if you dont define one), I did fix the bug that caused a 500 to be thrown when trying to request a non existing favicon tho.

2024-05-13 17:16 UTC, kashike requested changes

2024-05-13 17:16 UTC, kashike commented on src/main/java/com/seiama/javaducks/injection/OutdatedBannerInjection.java
> +      this.template = Files.readString(Path.of(Objects.requireNonNull(getClass().getClassLoader().getResource("outdated-banner.html")).toURI()));
Can we use a [`Resource`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/io/Resource.html)/[`ClassPathResource`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/io/ClassPathResource.html) instead?

2024-05-13 17:16 UTC, kashike commented on src/main/java/com/seiama/javaducks/service/InjectionService.java
> +public class InjectionService {
```suggestion
public class JavadocInjector {
```

2024-05-13 17:16 UTC, kashike commented on src/main/java/com/seiama/javaducks/controller/JavadocController.java
> +  private final InjectionService injectionService;
```suggestion
  private final JavadocInjector injector;
```

2024-05-13 17:17 UTC, kashike commented on src/main/java/com/seiama/javaducks/injection/FaviconInjection.java
> +    return file.toString().endsWith(".html");
Constant for `".html"`.

2024-05-13 17:42 UTC, powercasgamer requested changes

2024-05-13 17:42 UTC, powercasgamer commented on src/main/java/com/seiama/javaducks/injection/DuckInjection.java
> +    return file.toString().endsWith(".html");
```suggestion
    return file.toString().endsWith(HTML);
```

2024-05-13 17:43 UTC, powercasgamer commented on src/main/java/com/seiama/javaducks/injection/DuckInjection.java
> +  @Override
```suggestion
public class DuckInjection implements Injection {

  @Override
```

2024-05-13 17:43 UTC, powercasgamer requested changes
To match the other injectors

2024-05-13 17:47 UTC, MiniDigger commented on src/main/java/com/seiama/javaducks/injection/DuckInjection.java
> +    return file.toString().endsWith(".html");
good catch

2024-05-13 18:31 UTC, kashike approved these changes

2024-05-13 18:31 UTC, merged